### ISSUE TITLE
OneHotEncoder with many categories results in huge memory consumption

### ISSUE THREAD

**Issue by yolking** [online-ml/river#1253]
Hello again. I have memory issue, which probably may be not considered as issue from `river` perspective. 
Let's say I want to estimate model with one standartscaled feature and categorical feature having many categories. 
First I try to do this in sklearn, using:

```py
from sklearn import datasets
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PolynomialFeatures
from river import preprocessing
from river.compose import Select
from river import compat
import numpy as np
import pandas as pd

np.random.seed(1000)
X,y = datasets.make_regression(n_samples=5000000, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(1, 100, X.shape[0])
X['cat'] = X['cat'].astype('string')
y = pd.Series(y)

cat_feat2 = make_pipeline(
    ColumnTransformer(
        [('cat', OneHotEncoder(drop='first',handle_unknown='ignore'), ['cat']),
         ('feat2', StandardScaler(), ['feat_2'])],
        remainder='drop'),
    PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
)
reg = make_pipeline(ColumnTransformer(transformers=[
    ('cat_feat_2_inter', cat_feat2, ['cat', 'feat_2'])],remainder='drop'),
    SGDRegressor()
    )
reg.fit(X,y)      
``` 

This works fine and almost doesn't consume significant additional memory, though this transformation produces around 4000 extra zero columns due to all useless possible PolynomialFeatures between categorical variables.

Now I try to do similar thing (basically calling `partial_fit` instead of `fit` and producing right set of interactions) using `river`.

```py
group1 = Select('cat') | preprocessing.OneHotEncoder(sparse=True) 
group2 = Select('feat_2') | preprocessing.StandardScaler()
model = group1 + group1*group2  | compat.convert_sklearn_to_river(SGDRegressor())

model.predict_many(X)
model.learn_many(X,y)
```
This code seems to consume up to 20GB extra memory during calculations, while not suffering from extra 4000 columns as `sklearn` pipeline does. First memory consumption jumps on like 4-5GB on `predict_many` call and largest jump happens on `learn_many` call. 
If I use small number of categories then `river` realization also doesn't consume extra significant amount of memory during calculations. I think it's not model specific, but I had troubles combining demo with LinearRegression so I am not sure. This may be not seen as an issue from batch perspective but it makes first fit on huge data problematic for me, resulting in not enough memory errors. I can bypass this by splitting data, but still `sklearn` seems to not have this problem

**Comment by MaxHalford** [comment]
Ok I fixed this in #1254. River's `OneHotEncoder` will now output sparse dataframes, which are much less memory hungry.

There is a still a performance issue. The River script takes 48s to train on my chain, while the sklearn one takes only 7s. I'm not yet exactly sure why. One culprit seems to be the `TransformerProduct`'s `transform_many` method, which isn't vectorized. But one also has to check if a sparse dataframe is correctly passed to the `SGDRegressor`.

**Comment by MaxHalford** [comment]
@yolking can I let you install the development version and see if this works better for you?

**Comment by yolking** [comment]
It seems it became worse for me. Now I see up to 35gb additional memory consumption for this code.

**Comment by MaxHalford** [comment]
That's weird, I can't reproduce that. Can you reshare the problematic code snippet?

**Comment by yolking** [comment]
Same code:
```
from sklearn import datasets
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PolynomialFeatures
from river import preprocessing
from river.compose import Select
from river import compat
import numpy as np
import pandas as pd

np.random.seed(1000)
X,y = datasets.make_regression(n_samples=5000000, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(1, 100, X.shape[0])
X['cat'] = X['cat'].astype('string')
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder() 
group2 = Select('feat_2') | preprocessing.StandardScaler()
model = group1 + group1*group2  | compat.convert_sklearn_to_river(SGDRegressor())
model.predict_many(X)
model.learn_many(X,y)
```

![image](https://github.com/online-ml/river/assets/13572479/fcfc9093-08c4-4713-acff-62772ee8b17b)

Idk, maybe different pandas/numpy versions are to blame if you can't replicate.

**Comment by MaxHalford** [comment]
Thanks, I'll try to take a look this weekend.

**Comment by MaxHalford** [comment]
Honestly I'm not able to reproduce this issue. I'm using the following deps:

```
numpy==1.24.2
pandas==1.5.3
scikit-learn==1.2.2
```

**Comment by yolking** [comment]
I tried several combinations of dependencies and I get same problem every time. Anyway I looked at [this line](https://github.com/online-ml/river/blob/395468aefa3175b84cd3eb03dce5aedd2d1a1b94/river/compat/sklearn_to_river.py#L93) in debugger. Transformed X dataframe consumes a lot of memory there. I checked X dataframe columns dtypes:
`X.dtypes`

```
cat_1*feat_2       Sparse[object, 0]
cat_10*feat_2      Sparse[object, 0]
cat_11*feat_2      Sparse[object, 0]
cat_12*feat_2      Sparse[object, 0]
cat_13*feat_2      Sparse[object, 0]
                        ...         
cat_5            Sparse[bool, False]
cat_6            Sparse[bool, False]
cat_7            Sparse[bool, False]
cat_8            Sparse[bool, False]
cat_9            Sparse[bool, False]
Length: 98, dtype: object
```
As you can see interactions have `Sparse[object, 0]` dtype which is probably wrong  and appears as result of interaction with bool columns. And this dtype is obviously consuming more memory. If I convert such columns with `astype(pd.SparseDtype(float))`, X dataframes takes 3 times less space in memory. So I think this creates problems for me

**Comment by MaxHalford** [comment]
That's a good point. I'll take another look :)

**Comment by MaxHalford** [comment]
Ok so I've pinpointed the issue:

```py
encoder = compose.Select('cat') | preprocessing.OneHotEncoder()
one_hot = encoder.transform_many(X)
(one_hot['cat_1'] * X['feat_1']).sparse.density
```

```
1.0
```

The density should be much lower. In fact, it should be equal to `one_hot['cat_1'].sparse.density`, which in my case was `0.0101284`. It seems that multiplying a sparse `uint8` column by a `float` doesn't produce the expected sparse `float` column. I will try to find a fix.

**Comment by MaxHalford** [comment]
@yolking I believe the fix I just pushed should do the trick. The memory usage is much lower, and the `SGDRegressor` fits much faster.

**Comment by yolking** [comment]
It seems it broke something else for me) New code does not tolerate non-unique indices probably due to move to pandas operations.
Using my own data having non-unique indices on `model.predict_many(X)` call I first get warning
```
C:\Users\yolking\MyEnv\venv\lib\site-packages\river\compose\union.py:301: RuntimeWarning: '<' not supported between instances of 'int' and 'Timestamp', sort order is undefined for incomparable objects.
  return pd.concat( 
```
and then error:
```
---------------------------------------------------------------------------
InvalidIndexError                         Traceback (most recent call last)
Cell In[22], line 4
      3 model = group1 + group1*group2  | compat.convert_sklearn_to_river(SGDRegressor())
----> 4 model.predict_many(X)

File ~\MyEnv\venv\lib\site-packages\river\compose\pipeline.py:797, in Pipeline.predict_many(self, X)
    795 def predict_many(self, X: pd.DataFrame):
    796     """Call transform_many, and then predict_many on the final step."""
--> 797     X, last_step = self._transform_many(X=X)
    798     return last_step.predict_many(X=X)

File ~\MyEnv\venv\lib\site-packages\river\compose\pipeline.py:775, in Pipeline._transform_many(self, X)
    772     elif not t._supervised:
    773         t.learn_many(X=X)
--> 775     X = t.transform_many(X=X)
    777 last_step = next(steps)
    778 return X, last_step

File ~\MyEnv\venv\lib\site-packages\river\compose\union.py:301, in TransformerUnion.transform_many(self, X)
    299 def transform_many(self, X):
    300     """Passes the data through each transformer and packs the results together."""
--> 301     return pd.concat(
    302         (t.transform_many(X) for t in self.transformers.values()),
    303         copy=False,
    304         axis=1,
    305     )

File ~\MyEnv\venv\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\MyEnv\venv\lib\site-packages\pandas\core\reshape\concat.py:381, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    159 """
    160 Concatenate pandas objects along a particular axis.
    161 
   (...)
    366 1   3   4
    367 """
    368 op = _Concatenator(
    369     objs,
    370     axis=axis,
   (...)
    378     sort=sort,
    379 )
--> 381 return op.get_result()

File ~\MyEnv\venv\lib\site-packages\pandas\core\reshape\concat.py:612, in _Concatenator.get_result(self)
    610         obj_labels = obj.axes[1 - ax]
    611         if not new_labels.equals(obj_labels):
--> 612             indexers[ax] = obj_labels.get_indexer(new_labels)
    614     mgrs_indexers.append((obj._mgr, indexers))
    616 new_data = concatenate_managers(
    617     mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
    618 )

File ~\MyEnv\venv\lib\site-packages\pandas\core\indexes\base.py:3904, in Index.get_indexer(self, target, method, limit, tolerance)
   3901 self._check_indexing_method(method, limit, tolerance)
   3903 if not self._index_as_unique:
-> 3904     raise InvalidIndexError(self._requires_unique_msg)
   3906 if len(target) == 0:
   3907     return np.array([], dtype=np.intp)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```
But I see great improvements for `predict_many` call: only adequate memory usage increase.  
`learn_many` call still consumes a lot of memory, but less than before. 

Sklearn's transformed X for example in this thread
```
<5000000x4950 sparse matrix of type '<class 'numpy.float64'>'
	with 14898716 stored elements in Compressed Sparse Row format> 
```
is crazy efficient compared to this sparse realization and that's why any significant increase in X transformed size results in significant additional memory usage for me

**Comment by yolking** [comment]
I think maybe I should be providing something like scipy.sparse.csr_matrix(model.transform_many(X)) as argument for learn_many call and hence SGDRegressor if this works

**Comment by yolking** [comment]
```
group1 = Select('cat') | preprocessing.OneHotEncoder() 
group2 = Select('feat_2') | preprocessing.StandardScaler()
model1 = group1 + group1*group2  
model2 = compat.convert_sklearn_to_river(SGDRegressor())

model1.learn_many(X)
X_t = model1.transform_many(X)
X_t = scipy.sparse.csr_matrix(X_t.sparse.to_coo())
model2.estimator.partial_fit(X_t,y)
```
this code doesn't consume additional memory. Not great from pipeline perspective - maybe `csr_matrix` step should be added as transformer to the library in the future if library's standard estimators currently don't like this format. But it seems this solves all problems for me except for nice looking code:)

**Comment by MaxHalford** [comment]
I'm not able to reproduce the duplicate index issue. Do you have a working example?

Regarding the sparse thing. CSR is preferable to COO for SGDRegressor, right? I'm not sure what the best way to proceed is, in terms of nice looking code 🤔

**Comment by yolking** [comment]
This code triggers error now due to duplicated indices but wasn't triggering in previous versions:
```
np.random.seed(1000)
X,y = datasets.make_regression(n_samples=500, n_features=2)
X = pd.DataFrame(X)
X.index = [i  if i<250 else i-250 for i in range(500)]
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(1, 50, X.shape[0])
X['cat'] = X['cat'].astype('string')
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder()
group2 = Select('feat_2') | preprocessing.StandardScaler()
model = group1 + group1*group2  | compat.convert_sklearn_to_river(SGDRegressor())
model.predict_many(X)
model.learn_many(X,y)
```

Regrading SGDRegressor yes, it seems it's very optimized towards CSR so at least for him it should be desirable to provide in this exact format. The obvious way is to modify [here](https://github.com/online-ml/river/blob/dedb8dd14ae490c5197469a4857e78751556d74d/river/compat/sklearn_to_river.py#L92) as 
```
def learn_many(self, X, y):
        self.estimator.partial_fit(X=X.sparse.to_coo().tocsr(), y=y.values)
        return self
```
This should let me use `river` pipeline as indented. But maybe this brakes something else idk. 
`predict_many` method may also benefit from CSR input so it maybe required to do this in multiple places. 
I think all this should be true for SKL2RiverClassifier too

**Comment by MaxHalford** [comment]
Ok I fixed the duplicated index issue, it was a silly mistake.

Regarding the sparse thingie, with the latest dev version, you can do this:

```py
from sklearn import datasets
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PolynomialFeatures
from river import preprocessing
from river.compose import Select
from river import compose
from river import compat
import numpy as np
import pandas as pd

np.random.seed(1000)
X,y = datasets.make_regression(n_samples=5000000, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(1, 100, X.shape[0])
X['cat'] = X['cat'].astype('string')
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder() 
group2 = Select('feat_2') | preprocessing.StandardScaler()
model = (
    (group1 + group1*group2) |
    compose.FuncTransformer(lambda X: X.sparse.to_coo().tocsr()) |
    compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
model.learn_many(X,y)
model.predict_many(X)
```

That runs in 15s on my laptop. But it doesn't seem to bring any performance boost compared to not using the `FuncTransformer` 🤔

**Comment by yolking** [comment]
Unfortunately, if there is any non-sparse column present it results in error:
```
model = (
    (group1 + group1*group2 + group2) |
    compose.FuncTransformer(lambda X: X.sparse.to_coo().tocsr()) |
    compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
```
`AttributeError: Can only use the '.sparse' accessor with Sparse data.`

**Comment by yolking** [comment]
I tried running demo from first example in this thread (without explicit use of CSR) and it works fine without extra memory consumption after installing [this commit](https://github.com/online-ml/river/commit/c335e3bea58588545f04b0b5a45454e37b6665da).

So it seems parsing `X.values` was the reason behind my memory issues during `partial_fit` call. No need for `FuncTransformer` and tocsr() anymore. 
Specifically, calculating `X.values` allocates a lot of memory cause converts everything to `np.float64` and looses that tasty sparse efficiency. You dropped `.values` and now problem is gone.
I was just lucky with CSR and bypassed `X.values` call, but maybe CSR is not required in reality.
It should have been obvious, I got used to `.values`/`to_numpy` being casually called for such tasks and it even didn't cross my mind that sometimes it's wrong. 

Now I don't any memory issue for demo in this thread. But I still have memory issue with my own data, I'll try to analyze that tomorrow and report if this is library issue or my own and whether CSR helps.

**Comment by MaxHalford** [comment]
Good catch once again @yolking. I'm glad we're making progress. Apologies for the lack of research and precision on my side, I'm working on this in between many other things.

> On first look it seems if any columns aren't sparse, sklearn switches whole dataframe back to dense:

I guess that makes sense, right? Maybe a `FuncTransformer` that casts the DataFrame to sparse is the solution?

**Comment by yolking** [comment]
Yes, I looked for possible ways to cast, it seems the only efficient way is to do this column by columns somehow like this:
```
SparseTransformer = lambda X: X.astype({key: pd.SparseDtype(X.dtypes[key].type, fill_value=0) for key in X.dtypes.keys()})

model = ((group1 + group1*group2 + group2) |
        compose.FuncTransformer(SparseTransformer) |
        compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
```
This currently seems like the best solution for me. 
Among alternatives adding CSR cast:
`SparseTransformer = lambda X: X.astype({key: pd.SparseDtype(X.dtypes[key].type, fill_value=0) for key in X.dtypes.keys()}).sparse.to_coo().tocsr()`
makes no difference for me in terms of memory usage and even creates problem sometimes here:
```
    105 except exceptions.NotFittedError:
--> 106     return pd.Series([0] * len(X), index=X.index)

File ~\MyEnv\venv\lib\site-packages\scipy\sparse\_base.py:345, in spmatrix.__len__(self)
    344 def __len__(self):
--> 345     raise TypeError("sparse matrix length is ambiguous; use getnnz()"
    346                     " or shape[0]")
TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
```
 Both 
`SparseTransformer = lambda X: sparse.coo_matrix(X).tocsr()` 
`SparseTransformer = lambda X: sparse.csr_matrix(X)`
consume a lot of memory, so no go.

**Comment by yolking** [comment]
I've notices new issue with OneHotEncoder. It seems it currently behaves strangely if categorical variable is int:
```
X,y = datasets.make_regression(n_samples=6, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(1, 3, X.shape[0])
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder()
group2 = Select('feat_2') | preprocessing.StandardScaler()
SparseTransformer = lambda X: X.astype({key: pd.SparseDtype(X.dtypes[key].type, fill_value=0) for key in X.dtypes.keys()})
model = (
    (group1 + group1*group2) |
    compose.FuncTransformer(SparseTransformer) |
    compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
model.predict_many(X)
model.transform_many(X)
```
This results in `cat` and `cat*feat_2` columns, which shouldn't be present and all values are wrong
```
   cat*feat_2  cat_1*feat_2  cat_2*feat_2  cat  cat_1  cat_2
0   -0.116142           0.0           0.0    2      0      0
1   -0.219363           0.0           0.0    1      0      0
2    1.305341           0.0           0.0    1      0      0
3    2.326312           0.0           0.0    2      0      0
4   -1.199819           0.0           0.0    2      0      0
5   -1.591153           0.0           0.0    1      0      0
```
Not sure if this is new or old problem

**Comment by yolking** [comment]
I noticed, that if any category is encoded as zero, that results in wrong OneHotEncoder result:
```
np.random.seed(1000)
X,y = datasets.make_regression(n_samples=6, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(0, 3, X.shape[0])
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder()
group2 = Select('feat_2') | preprocessing.StandardScaler()
SparseTransformer = lambda X: X.astype({key: pd.SparseDtype(X.dtypes[key].type, fill_value=0) for key in X.dtypes.keys()})
model = (
    (group1) |
    compose.FuncTransformer(SparseTransformer) |
    #compose.FuncTransformer(lambda X: sparse.coo_matrix(X)) |
    compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
model.predict_many(X)
print(model.transform_many(X))
```
All categories are present in output, _0 category isn't dropped:
   cat_0  cat_1  cat_2
0      0      1      0
1      0      0      1
2      1      0      0
3      0      1      0
4      0      1      0
5      0      0      1

**Comment by MaxHalford** [comment]
I just added a `drop_first` parameter, which removes the `min(columns)` column if `True`. Is that what you're looking for?

**Comment by yolking** [comment]
Yes, thank you. it's important against perfect multicollinearity. But it throws error for me: 
```
np.random.seed(1000)
X,y = datasets.make_regression(n_samples=6, n_features=2)
X = pd.DataFrame(X)
X.columns = ['feat_1','feat_2']
X['cat'] = np.random.randint(0, 3, X.shape[0])
y = pd.Series(y)

group1 = Select('cat') | preprocessing.OneHotEncoder(drop_first=True)
group2 = Select('feat_2') | preprocessing.StandardScaler()
model = (
    (group1) |
    compat.convert_sklearn_to_river(SGDRegressor(max_iter=3))
)
model.predict_many(X)
```

`KeyError: "['cat'] not found in axis"`

**Comment by MaxHalford** [comment]
Jesus I'm making so many little mistakes 😅

Fixed ✅

**Comment by yolking** [comment]
Thank you for all the changes.
I think everything feasible was improved here. I still see some much lesser spikes in memory usage, but for now I don't see any reasonable fixes. I'll reopen if I come up with anything
